language: python

jobs:
  include:
    - services: docker

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_BUILD="cp36-* cp37-* cp38-*"
    - CIBW_BEFORE_BUILD="pip install tensorflow && sed -i 's/libresolv.so.2\"/libresolv.so.2\", \"libtensorflow_framework.so.2\"/g' \$(find / -name policy.json)"
    - CIBW_SKIP="*-win32 *-manylinux_i686"

install:
  - git clone https://github.com/deepmodeling/deepmd-kit -b v1.2.2
  - cd deepmd-kit
  - python -m pip install -U pip twine cibuildwheel scikit-build tensorflow==2.3

script:
  - python -m cibuildwheel --output-dir wheelhouse
  - python setup.py sdist

after_success:
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*; python -m twine upload dist/*.tar.gz; fi
