name: Build and upload to PyPI

on:
  push:
    branches:
      - dpgen
    tags:
      - v*
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]  #, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'deepmodeling/dpgen'
          ref: 'v0.9.1'
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD: "cp36-* cp37-* cp38-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686"
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'deepmodeling/dpgen'
          ref: 'v0.9.1'
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
      - run: pip install -U scikit-build tensorflow setuptools_scm
      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
